name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rebloom:
        image: redislabs/rebloom:latest
        ports:
          - 6379:6379
      redisearch:
        image: redislabs/redisearch:latest
        ports:
          - 6380:6380

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean install -DskipTests=true --file pom.xml

      - name: Test RedisBloom
        run: mvn test -pl redisbloom --file pom.xml
        env:
          REDIS_HOST: localhost

      - name: Test RediSearch
        run: mvn test -pl redisearch --file pom.xml
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6380
