name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rebloom:
        image: redislabs/rebloom:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      redisearch:
        image: redislabs/redisearch:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6380:6380

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean install -DskipTests=true --file pom.xml

      - name: Test RedisBloom
        run: mvn test -pl redisbloom -DREDIS_HOST=localhost --file pom.xml

      - name: Test RediSearch
        run: mvn test -pl redisearch -DREDIS_HOST=localhost -DREDIS_PORT=6380 --file pom.xml