name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rebloom:
        image: redislabs/rebloom:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          REDIS_HOST: localhost
